import Head from "next/head";
import Link from "next/link";

const Layout = ({children, title = 'Crypto Tracker'}) => {
    return (
        <div className='layout'>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header className='header'>
                <Link href='/' passHref>
                    <a>
                        {/*<img src="../img.png" className={'img_logo'} alt={title}/>*/}
                        <div className="banner">
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                            <div className="pannel"></div>
                        </div>
                    </a>
                </Link>
            </header>
            <main>{children}</main>
        </div>
    )
}

export default Layout